//
//  AdManager.swift
//  Car Auctions
//  this file manages all new ads and stores them to the remote Firestore database
//  Created by Warren Elliott on 02/07/2020.
//  Copyright © 2020 Warren Elliott. All rights reserved.
//

import Foundation
import Firebase

class AdManager{
    
    let db = Firestore.firestore() //init Firebase
    let storage = Storage.storage() //init storage

    
    func uploadDatabaseDestination(_ draft: Bool) -> String{
        
        let destination = (draft ? "DraftsDatabase" : "LiveDatabase")
        return destination
        
    } // function dictates wether this will be uploaded in the Drafts or live, based on condition
    
    func uploadAd(_ ad: AuctionSaleData){
        
        let adImagesStorage = self.storage.reference() //reference to the storage on Firebase
        let adImageRef = adImagesStorage.child("UserUploadedImagesDraft/ \(ad.adId)")
        // storage destination in Firebase
        let detailsReference = self.db.collection(uploadDatabaseDestination(ad.isDraft)).document("adNo__\(ad.adId)")
        
        //gives the ad an ID in Firebase for reference
        
        let detailsData = [
            "adID" : ad.adId,
            "adAuthor" : ad.adAuthor,
            "adName" : ad.adName,
            "adDescription" : ad.adDescription,
            "adBid" : ad.adBid,
            "adEndingDate" : ad.adEndingDate,
            "adEndingTime" : ad.adEndingTime,
            "adPosted" : ad.datePosted,
            "isDraft" : ad.isDraft,
            "adLocation" : ad.adLocation,
            "bidCount" : ad.bidCount
            ] as [String : Any] //creates a little data dictionary to dictate how data will be stored in the database
    
        detailsReference.setData(detailsData, completion: { (error) in
            if let err = error{
                print (err.localizedDescription)
            }
        })
        
        var urlStrings = [String]() //list of URL's where the images that belong to this ad are stored remotely
        
        for photo in ad.adImages{ //photo uploader
            
            guard let data = photo?.jpegData(compressionQuality: 1.0) else{return} //converts image
            let imageName = UUID().uuidString //give a unique ID  generated by Swift to the image
            let imageReference = adImageRef.child(imageName) //instructions on how to store it
            
            imageReference.putData(data, metadata: nil) { (metadata, error) in
                if let error = error{
                    print (error.localizedDescription)
                    return
                }
                
                else{
                    imageReference.downloadURL { (url, error) in
                        if let error = error{
                            print (error.localizedDescription)
                            return
                        }
                        else{
                            guard let url = url else{
                                return
                            }
                            
                            
                            
                            let urlString = url.absoluteString
                            urlStrings.append(urlString)
                            //let dataReference = self.db.collection(self.uploadDatabaseDestination(ad.isDraft)).document("adNo__\(ad.adId)").collection("AdImages").document() //uploads the ad in the correct databse
                            //let dataReference = self.db.collection(self.uploadDatabaseDestination(ad.isDraft)).document("adNo__\(ad.adId)") //uploads the ad in the correct databse
//                            let documentUID = dataReference.documentID
//                            let data = ["UID": documentUID, "URL": urlString]
                            
                            
                            
                            detailsReference.updateData(["imageURLs" : urlStrings]) { (error) in
                                if let err = error{
                                    print (err.localizedDescription)
                                }
                            }
                            
//                            dataReference.setData(data, completion: { (error  ) in
//                                if let err = error{
//                                    print (err.localizedDescription)
//                                }
//                            })
                        }
                    }
                }
            }
        }
        
    }
}

